# -*- coding: utf-8 -*-
"""Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsnDgHZckSCvz9QFWfM20Xv1pLez1rFv
"""

!pip install boruta
!pip install pingouin
!pip install python-docx

import math
import itertools
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import numpy as np
import pandas as pd
import random
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import warnings


from boruta import BorutaPy
from docx import Document
from itertools import combinations
from math import isnan
from matplotlib.colors import Normalize
from matplotlib.cm import get_cmap
from matplotlib.colors import LinearSegmentedColormap,to_hex
from matplotlib.lines import Line2D
from matplotlib.patches import Ellipse, Patch
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from pingouin import compute_effsize, power_ttest
from scipy.interpolate import griddata
from scipy.stats import chi2, ttest_ind, pearsonr, ttest_rel, sem
from scipy.spatial.distance import mahalanobis
from scipy.special import comb, expit
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression, RANSACRegressor, TheilSenRegressor, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import resample
from statsmodels.stats.power import TTestIndPower, FTestPower
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.anova import AnovaRM, anova_lm
from statsmodels.formula.api import ols, mixedlm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multitest import multipletests

file_path_xlsx = '/content/data.xlsx'
df = pd.read_excel(file_path_xlsx, sheet_name="dataset")
print(df.head())

#BORUTA Analysis
df_copy = df.copy()
df_X = df_copy.drop(df_copy.columns[[0, 10]], axis=1)
y = df_copy.iloc[:, 10]

# 2. Détection des variables catégorielles
categorical_cols = df_X.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_cols = df_X.select_dtypes(include=[np.number]).columns.tolist()

# 3. Encodage one-hot pour les variables catégorielles
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_cols),
        ('cat', OneHotEncoder(drop='first', sparse_output=False), categorical_cols)
    ]
)

# 4. Pipeline avec RandomForest et Boruta
X_encoded = preprocessor.fit_transform(df_X)
feature_names = numerical_cols + list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols))

# Boruta attend une ndarray
rf = RandomForestRegressor(n_jobs=-1, max_depth=15, min_samples_leaf=5, random_state=42)
boruta = BorutaPy(estimator=rf, n_estimators='auto', verbose=0, random_state=42)
boruta.fit(X_encoded, y)


# 5. Récupération des résultats
importances = boruta.ranking_
selected = boruta.support_
feature_importance = pd.DataFrame({
    'Feature': feature_names,
    'Rank': importances,
    'Selected': selected
}).sort_values(by='Rank', ascending=True)

# 6. Visualisation
plt.figure(figsize=(10, max(6, len(feature_importance) * 0.4)))
bars = plt.barh(
    feature_importance['Feature'],
    feature_importance['Rank'],
    edgecolor='black',
    linewidth=0.8,
    color=['forestgreen' if sel else 'red' for sel in feature_importance['Selected']]
)

plt.xlabel("Rank (Degree of importance)")
plt.ylabel("Features")
plt.title("Feature ranking (Boruta)")
plt.gca().invert_yaxis()  # Inverser l'axe Y pour que le plus important soit en haut
plt.tight_layout()
sns.despine(offset=2, trim=True)
plt.show()

# Model Comparison
top3_vars = feature_importance[feature_importance['Selected']].sort_values(by='Rank').head(3)['Feature'].tolist()

# 2. Créer toutes les combinaisons possibles (1 à 3 variables)
all_models = []
for k in range(1, len(top3_vars)+1):
    for combo in itertools.combinations(top3_vars, k):
        all_models.append(list(combo))

# 3. Encodage complet (déjà fait précédemment)
X_all_encoded_df = pd.DataFrame(X_encoded, columns=feature_names)

# 4. Calcul R² ajusté et Cp
model_stats = []
n = len(y)
full_model = sm.OLS(y, sm.add_constant(X_all_encoded_df[top3_vars])).fit()
sigma2 = full_model.mse_resid

for vars_ in all_models:
    X_subset = sm.add_constant(X_all_encoded_df[vars_])
    model = sm.OLS(y, X_subset).fit()
    p = X_subset.shape[1]
    RSS = ((model.resid) ** 2).sum()
    Cp = RSS / sigma2 - (n - 2 * p)
    model_stats.append({
        'Variables': ', '.join(vars_),
        'R2_adj': model.rsquared_adj,
        'Cp': Cp
    })

df_models = pd.DataFrame(model_stats).sort_values(by='R2_adj', ascending=False).reset_index(drop=True)

# 5. Barplot combiné (R² et Cp)
plt.figure(figsize=(12, 0.6 * len(df_models)))
y_pos = np.arange(len(df_models))

bar_width = 0.4
plt.barh(y_pos - bar_width/2, df_models['R2_adj'], height=bar_width, color='lightblue', edgecolor='black', label='Adjusted R²')
plt.barh(y_pos + bar_width/2, df_models['Cp'], height=bar_width, color='#FEDA75', edgecolor='black', label='Mallow CP')

# Affichage des valeurs
for i, (r2, cp) in enumerate(zip(df_models['R2_adj'], df_models['Cp'])):
    plt.text(r2 + 0.01, i - bar_width/2, f"{r2:.3f}", va='center')
    plt.text(cp + 0.5, i + bar_width/2, f"{cp:.2f}", va='center')

plt.yticks(y_pos, df_models['Variables'])
plt.xlabel("Values")
plt.title("Model comparison (3 best features selected with BORUTA)")
plt.legend()
plt.tight_layout()
sns.despine(offset=2, trim=True)
plt.show()

# Regression analysis + stats 1.0
# If we want to assess MI effect upon accuracy
df_statistics = df.iloc[:, [0, 10, 1]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 3:
    col_type = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if col_type:
        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]
        x_var = df_statistics.columns[2]

        df_statistics = df_statistics.groupby(participant, as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        df_statistics["mahal_dist"] = mahalanobis_distance(df_statistics, [x_var, y_var])
        threshold = np.percentile(df_statistics["mahal_dist"], 66)
        df_selected = df_statistics[df_statistics["mahal_dist"] <= threshold].copy()
        df_selected["mahal_dist"] = mahalanobis_distance(df_selected, [x_var, y_var])

        cov = np.cov(df_selected[[x_var, y_var]].T)
        mean_x, mean_y = df_selected[x_var].mean(), df_selected[y_var].mean()
        eigvals, eigvecs = np.linalg.eigh(cov)
        angle = np.degrees(np.arctan2(*eigvecs[:, 0][::-1]))
        width, height = 2 * np.sqrt(chi2.ppf(0.95, 2) * eigvals)

        X = df_statistics[[x_var]].values
        y = df_statistics[y_var].values
        X_pred = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)

        models = {
            "OLS representation": {
                "model": LinearRegression(),
                "style": {"linestyle": "-", "label": "OLS"}
            },
            "RANSAC representation": {
                "model": RANSACRegressor(),
                "style": {"linestyle": "dotted", "label": "RANSAC"}
            },
            "Theil Sen representation": {
                "model": TheilSenRegressor(),
                "style": {"linestyle": "dashed", "label": "Theil-Sen"}
            }
        }

        fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True)
        color = my_palette[0]

        for ax, (title, config) in zip(axes, models.items()):
            model = config["model"]
            model.fit(X, y)
            y_pred = model.predict(X_pred)

            inliers = df_statistics[df_statistics["mahal_dist"] <= threshold]
            outliers = df_statistics[df_statistics["mahal_dist"] > threshold]


            sns.scatterplot(data=inliers, x=x_var, y=y_var, color=color, edgecolor="black", ax=ax)
            ax.scatter(
                outliers[x_var],
                outliers[y_var],
                color=color,
                marker="x",
                s=40,
                label="Outlier"
            )

            ax.plot(X_pred, y_pred, color=color, linestyle=config["style"]["linestyle"], linewidth=0.8)
            x_pad = 0.05 * (df_statistics[x_var].max() - df_statistics[x_var].min())
            y_pad = 0.05 * (df_statistics[y_var].max() - df_statistics[y_var].min())
            ax.set_xlim(df_statistics[x_var].min() - x_pad, df_statistics[x_var].max() + x_pad)
            ax.set_ylim(df_statistics[y_var].min() - y_pad, df_statistics[y_var].max() + y_pad)

            ax.set_xlabel(x_var)
            ax.set_ylabel(y_var)

            sns.despine(ax=ax, top=True, right=True, trim=True)

        handles = [
            plt.Line2D([], [], color=color, linestyle="-", label="OLS"),
            plt.Line2D([], [], color=color, linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color=color, linestyle="dashed", label="Theil-Sen"),
        ]
        axes[-1].legend(handles=handles, title="Model", loc="upper right")

        plt.tight_layout()
        plt.show()


        # TEST PCC - regression linéaire

        X_ols = sm.add_constant(X)
        model_ols = sm.OLS(y, X_ols).fit()
        r2_ols = model_ols.rsquared
        n = X.shape[0]
        p = X.shape[1]

        adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
        df_model = int(model_ols.df_model)
        df_resid = int(model_ols.df_resid)

        f_stat = model_ols.fvalue
        f_pvalue = model_ols.f_pvalue
        f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999

        power_analysis = FTestPower()
        power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

        n_iterations = 1000
        r2_adj_bootstrap = []

        for _ in range(n_iterations):
            X_sample, y_sample = resample(X, y, replace=True)
            X_sample_ols = sm.add_constant(X_sample)
            model_sample = sm.OLS(y_sample, X_sample_ols).fit()

            n_boot = X_sample.shape[0]
            p_boot = X_sample.shape[1]
            r2_boot = model_sample.rsquared
            r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
            r2_adj_bootstrap.append(r2_adj)

        ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
        ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

        ransac = RANSACRegressor()
        ransac.fit(X, y)
        y_pred_ransac = ransac.predict(X)

        theil_sen = TheilSenRegressor()
        theil_sen.fit(X, y)
        y_pred_theil = theil_sen.predict(X)

        mse_ols = mean_squared_error(y, model_ols.predict(X_ols))
        rmse_ols = np.sqrt(mse_ols)

        mse_ransac = mean_squared_error(y, y_pred_ransac)
        rmse_ransac = np.sqrt(mse_ransac)

        mse_theil = mean_squared_error(y, y_pred_theil)
        rmse_theil = np.sqrt(mse_theil)

        ss_total = np.sum((y - np.mean(y))**2)
        ss_res_ransac = np.sum((y - y_pred_ransac)**2)
        ss_res_theil = np.sum((y - y_pred_theil)**2)

        r2_ransac = 1 - (ss_res_ransac / ss_total)

        inliers_mask = ransac.inlier_mask_
        n_total = len(y)
        n_inliers = np.sum(inliers_mask)
        inlier_ratio = n_inliers / n_total

        r2_theil = 1 - (ss_res_theil / ss_total)

        n_features = X.shape[1]
        n_min = n_features + 1
        n_samples = X.shape[0]
        n_subsamples = min(300, comb(n_samples, n_min, exact=True))
        robustness_index = n_subsamples / n_min

        adjusted_r2_ransac = 1 - ((1 - r2_ransac) * (n - 1)) / (n - p - 1)
        adjusted_r2_theil = 1 - ((1 - r2_theil) * (n - 1)) / (n - p - 1)

        print("\nComparaison des modèles de régression :\n")
        print(f"OLS :\nR²= {r2_ols:.3f}\nadj.R²= {adjusted_r2_ols:.3f}\ndf model= {df_model} | residual= {df_resid}\np-value= {f_pvalue:.3f}\npower= {power:.3f}\nF-statistic = {f_stat:.3f}\nRMSE = {rmse_ols:.3f}\nIC adj.R²(95%)=[{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")
        print()
        print(f"RANSAC:\nR²= {r2_ransac:.3f}\nR² ajusté = {adjusted_r2_ransac:.3f}\nRMSE = {rmse_ransac:.3f}\nInlier Ratio={inlier_ratio:.3f} ({n_inliers}/{n_total})")
        print()
        print(f"Theil-Sen:\nR²= {r2_theil:.3f}\nR² ajusté = {adjusted_r2_theil:.3f}\nRMSE = {rmse_theil:.3f}\nRobustness Index= {robustness_index:.1f}")

# Regression analysis + stats using a covariate 1.0
# The solution for MI effect upon accuracy by condition (TMR versus control)
!pip install boruta
!pip install pingouin
!pip install python-docx

import math
import itertools
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import numpy as np
import pandas as pd
import random
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import warnings


from boruta import BorutaPy
from docx import Document
from itertools import combinations
from math import isnan
from matplotlib.colors import Normalize
from matplotlib.cm import get_cmap
from matplotlib.colors import LinearSegmentedColormap,to_hex
from matplotlib.lines import Line2D
from matplotlib.patches import Ellipse, Patch
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from pingouin import compute_effsize, power_ttest
from scipy.interpolate import griddata
from scipy.stats import chi2, ttest_ind, pearsonr, ttest_rel, sem
from scipy.spatial.distance import mahalanobis
from scipy.special import comb, expit
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression, RANSACRegressor, TheilSenRegressor, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import resample
from statsmodels.stats.power import TTestIndPower, FTestPower
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.anova import AnovaRM, anova_lm
from statsmodels.formula.api import ols, mixedlm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multitest import multipletests
# Удаляем лишние пробелы в названиях столбцов
df.columns = df.columns.str.strip()

# Копируем в новый DataFrame
df_statistics = df.copy()

df_statistics = df.iloc[:, [0, 10, 1, 11]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 4:
    is_3_cont = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()
    is_4_cont = df_statistics.iloc[:, 3].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if (is_3_cont and not is_4_cont) or (not is_3_cont and is_4_cont):
        print("Détection : 1 VI continue + 1 VI catégorielle multiclasses")

        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]

        if is_3_cont:
            x_var = df_statistics.columns[2]
            z_var = df_statistics.columns[3]
        else:
            x_var = df_statistics.columns[3]
            z_var = df_statistics.columns[2]

        # Regroupement
        df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        z_order = sorted(df_statistics[z_var].unique())
        palette_dict = dict(zip(z_order, my_palette))

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        models = {
            "OLS": {"model": LinearRegression(), "style": {"color": "red", "linestyle": "-", "label": "OLS"}},
            "RANSAC": {"model": RANSACRegressor(), "style": {"color": "red", "linestyle": "dotted", "label": "RANSAC"}},
            "Theil-Sen": {"model": TheilSenRegressor(), "style": {"color": "red", "linestyle": "dashed", "label": "Theil-Sen"}}
        }

        fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)

        for ax, (name, config) in zip(axes, models.items()):
            for condition in z_order:
                df_cond = df_statistics[df_statistics[z_var] == condition]

                df_cond["mahal_dist"] = mahalanobis_distance(df_cond, [x_var, y_var])
                threshold = np.percentile(df_cond["mahal_dist"], 66)
                df_sel = df_cond[df_cond["mahal_dist"] <= threshold].copy()

                inliers = df_cond[df_cond["mahal_dist"] <= threshold]
                outliers = df_cond[df_cond["mahal_dist"] > threshold]
                ax.scatter(inliers[x_var], inliers[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")
                ax.scatter(outliers[x_var], outliers[y_var],
                           c=palette_dict[condition],
                           marker="x", linewidth=1, s=120,
                           label=f"{z_var}={condition} outlier")

                if len(df_cond[x_var].unique()) < 2:
                    continue

                X_c = df_cond[[x_var]].values
                y_c = df_cond[y_var].values
                X_pred_c = np.linspace(X_c.min(), X_c.max(), 100).reshape(-1, 1)

                model = config["model"]
                model.fit(X_c, y_c)
                y_pred_c = model.predict(X_pred_c)

                ax.plot(X_pred_c, y_pred_c,
                        color=palette_dict[condition],
                        linestyle=config["style"]["linestyle"],
                        linewidth=0.8)

                ax.scatter(df_cond[x_var], df_cond[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")

            ax.set_xlabel(x_var)
            if ax == axes[0]:
                ax.set_ylabel(y_var)
            ax.set_title(name)
            sns.despine(ax=ax)

        handles = [
            plt.Line2D([], [], color="red", linestyle="-", label="OLS"),
            plt.Line2D([], [], color="red", linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color="red", linestyle="dashed", label="Theil-Sen")
        ] + [
            plt.Line2D([], [], marker='o', linestyle='', color=palette_dict[val],
                       label=f"{z_var}={val}", markeredgecolor="black", markersize=7)
            for val in z_order
        ]
        axes[-1].legend(handles=handles, loc="upper right")
        sns.despine(offset=2, trim=True)
        plt.tight_layout()
        plt.show()


        # TEST STATISTIQUE - ANCOVA
       #I have no idea why it didn't work, but atleast now it works
        df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })
        is_repeated = df_statistics.groupby(participant)[x_var].nunique().max() > 1
        # Corrected formula with backticks for column names - changed
        formula = f'{y_var} ~ Q("{x_var}") + Q("{z_var}")'

        model = ols(formula, data=df_statistics).fit()
        aov_table = anova_lm(model, typ=2)
        aov_table["eta²"] = aov_table["sum_sq"] / sum(aov_table["sum_sq"])
        print(aov_table)

        modalities = df_statistics[z_var].unique()
        if len(modalities) > 1:
            from itertools import combinations
            comparisons = list(combinations(modalities, 2))
            p_vals, labels = [], []

            for a, b in comparisons:
                group1 = df_statistics[df_statistics[z_var] == a][y_var]
                group2 = df_statistics[df_statistics[z_var] == b][y_var]
                t_stat, p_val = ttest_ind(group1, group2, equal_var=False)
                p_vals.append(p_val)
                labels.append((a, b))

            method = "bonferroni" if len(comparisons) > 2 else "holm"
            reject, pvals_corr, _, _ = multipletests(p_vals, method=method)

            found_significant = False

            for (a, b), p_raw, p_adj, keep in zip(labels, p_vals, pvals_corr, reject):
                if keep:
                    found_significant = True
                    print(f"{z_var} ({a} vs {b}) - raw p = {p_raw:.3f}, corrected p = {p_adj:.3f} [{method}]")

            if not found_significant:
                print("Aucune comparaison post-hoc significative détectée.")
                #Changed, such a drama queen actually
                x_var_q = f'Q("{x_var}")'
                p_val_x = aov_table.loc[x_var_q, "PR(>F)"]
                if p_val_x < 0.05:
                    print("\nEffet continu détecté: test de régression linéaire effectué)\n")

                    X = df_statistics[[x_var]].values
                    y = df_statistics[y_var].values

                    X_ols = sm.add_constant(X)
                    model_ols = sm.OLS(y, X_ols).fit()
                    r2_ols = model_ols.rsquared
                    n, p = X.shape

                    adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
                    df_model = int(model_ols.df_model)
                    df_resid = int(model_ols.df_resid)
                    f_stat = model_ols.fvalue
                    f_pvalue = model_ols.f_pvalue

                    f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999
                    power_analysis = FTestPower()
                    power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

                    # Bootstrap pour l'IC de R² ajusté
                    r2_adj_bootstrap = []
                    for _ in range(1000):
                        X_sample, y_sample = resample(X, y, replace=True)
                        X_sample_ols = sm.add_constant(X_sample)
                        model_sample = sm.OLS(y_sample, X_sample_ols).fit()
                        n_boot, p_boot = X_sample.shape
                        r2_boot = model_sample.rsquared
                        r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
                        r2_adj_bootstrap.append(r2_adj)

                    ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
                    ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

                    print(f"OLS:\nR² = {r2_ols:.3f}\nadj.R² = {adjusted_r2_ols:.3f}")
                    print(f"df model = {df_model} | residual = {df_resid}")
                    print(f"p-value = {f_pvalue:.3f} | power = {power:.3f} | F = {f_stat:.3f}")
                    print(f"RMSE = {np.sqrt(mean_squared_error(y, model_ols.predict(X_ols))):.3f}")
                    print(f"IC adj.R² (95%) = [{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")

# Regression analysis + stats using a covariate 2.0
# Strategies effect upon ISI with Condition (TMR vs Ctrl) as a covariate
!pip install boruta
!pip install pingouin
!pip install python-docx

import math
import itertools
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import numpy as np
import pandas as pd
import random
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import warnings


from boruta import BorutaPy
from docx import Document
from itertools import combinations
from math import isnan
from matplotlib.colors import Normalize
from matplotlib.cm import get_cmap
from matplotlib.colors import LinearSegmentedColormap,to_hex
from matplotlib.lines import Line2D
from matplotlib.patches import Ellipse, Patch
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from pingouin import compute_effsize, power_ttest
from scipy.interpolate import griddata
from scipy.stats import chi2, ttest_ind, pearsonr, ttest_rel, sem
from scipy.spatial.distance import mahalanobis
from scipy.special import comb, expit
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression, RANSACRegressor, TheilSenRegressor, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import resample
from statsmodels.stats.power import TTestIndPower, FTestPower
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.anova import AnovaRM, anova_lm
from statsmodels.formula.api import ols, mixedlm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multitest import multipletests
# Removed extra spaces in column names - the only way it worked
df.columns = df.columns.str.strip()

# Copying to a new DataFrame
df_statistics = df.copy()

df_statistics = df.iloc[:, [0, 1, 2, 11]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 4:
    is_3_cont = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()
    is_4_cont = df_statistics.iloc[:, 3].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if (is_3_cont and not is_4_cont) or (not is_3_cont and is_4_cont):
        print("Détection : 1 VI continue + 1 VI catégorielle multiclasses")

        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]

        if is_3_cont:
            x_var = df_statistics.columns[2]
            z_var = df_statistics.columns[3]
        else:
            x_var = df_statistics.columns[3]
            z_var = df_statistics.columns[2]

        # Regroupement
        df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        z_order = sorted(df_statistics[z_var].unique())
        palette_dict = dict(zip(z_order, my_palette))

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        models = {
            "OLS": {"model": LinearRegression(), "style": {"color": "red", "linestyle": "-", "label": "OLS"}},
            "RANSAC": {"model": RANSACRegressor(), "style": {"color": "red", "linestyle": "dotted", "label": "RANSAC"}},
            "Theil-Sen": {"model": TheilSenRegressor(), "style": {"color": "red", "linestyle": "dashed", "label": "Theil-Sen"}}
        }

        fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)

        for ax, (name, config) in zip(axes, models.items()):
            for condition in z_order:
                df_cond = df_statistics[df_statistics[z_var] == condition]

                df_cond["mahal_dist"] = mahalanobis_distance(df_cond, [x_var, y_var])
                threshold = np.percentile(df_cond["mahal_dist"], 66)
                df_sel = df_cond[df_cond["mahal_dist"] <= threshold].copy()

                inliers = df_cond[df_cond["mahal_dist"] <= threshold]
                outliers = df_cond[df_cond["mahal_dist"] > threshold]
                ax.scatter(inliers[x_var], inliers[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")
                ax.scatter(outliers[x_var], outliers[y_var],
                           c=palette_dict[condition],
                           marker="x", linewidth=1, s=120,
                           label=f"{z_var}={condition} outlier")

                if len(df_cond[x_var].unique()) < 2:
                    continue

                X_c = df_cond[[x_var]].values
                y_c = df_cond[y_var].values
                X_pred_c = np.linspace(X_c.min(), X_c.max(), 100).reshape(-1, 1)

                model = config["model"]
                model.fit(X_c, y_c)
                y_pred_c = model.predict(X_pred_c)

                ax.plot(X_pred_c, y_pred_c,
                        color=palette_dict[condition],
                        linestyle=config["style"]["linestyle"],
                        linewidth=0.8)

                ax.scatter(df_cond[x_var], df_cond[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")

            ax.set_xlabel(x_var)
            if ax == axes[0]:
                ax.set_ylabel(y_var)
            ax.set_title(name)
            sns.despine(ax=ax)

        handles = [
            plt.Line2D([], [], color="red", linestyle="-", label="OLS"),
            plt.Line2D([], [], color="red", linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color="red", linestyle="dashed", label="Theil-Sen")
        ] + [
            plt.Line2D([], [], marker='o', linestyle='', color=palette_dict[val],
                       label=f"{z_var}={val}", markeredgecolor="black", markersize=7)
            for val in z_order
        ]
        axes[-1].legend(handles=handles, loc="upper right")
        sns.despine(offset=2, trim=True)
        plt.tight_layout()
        plt.show()


# TEST STATISTIQUE - ANCOVA
#I have no idea why it didn't work, but atleast now it works
df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
    x_var: "mean",
    y_var: "mean"
})
is_repeated = df_statistics.groupby(participant)[x_var].nunique().max() > 1
# Corrected formula with backticks for column names - changed
# Wrapped the dependent variable in Q() - changed
formula = f'Q("{y_var}") ~ Q("{x_var}") + Q("{z_var}")'

model = ols(formula, data=df_statistics).fit()
aov_table = anova_lm(model, typ=2)
aov_table["eta²"] = aov_table["sum_sq"] / sum(aov_table["sum_sq"])
print(aov_table)

modalities = df_statistics[z_var].unique()
if len(modalities) > 1:
    from itertools import combinations
    comparisons = list(combinations(modalities, 2))
    p_vals, labels = [], []

    for a, b in comparisons:
        group1 = df_statistics[df_statistics[z_var] == a][y_var]
        group2 = df_statistics[df_statistics[z_var] == b][y_var]
        t_stat, p_val = ttest_ind(group1, group2, equal_var=False)
        p_vals.append(p_val)
        labels.append((a, b))

    method = "bonferroni" if len(comparisons) > 2 else "holm"
    reject, pvals_corr, _, _ = multipletests(p_vals, method=method)

    found_significant = False

    for (a, b), p_raw, p_adj, keep in zip(labels, p_vals, pvals_corr, reject):
        if keep:
            found_significant = True
            print(f"{z_var} ({a} vs {b}) - raw p = {p_raw:.3f}, corrected p = {p_adj:.3f} [{method}]")

    if not found_significant:
        print("Aucune comparaison post-hoc significative détectée.")
        #Changed, such a drama queen actually
        x_var_q = f'Q("{x_var}")'
        p_val_x = aov_table.loc[x_var_q, "PR(>F)"]
        if p_val_x < 0.05:
            print("\nEffet continu détecté: test de régression linéaire effectué)\n")

            X = df_statistics[[x_var]].values
            y = df_statistics[y_var].values

            X_ols = sm.add_constant(X)
            model_ols = sm.OLS(y, X_ols).fit()
            r2_ols = model_ols.rsquared
            n, p = X.shape

            adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
            df_model = int(model_ols.df_model)
            df_resid = int(model_ols.df_resid)
            f_stat = model_ols.fvalue
            f_pvalue = model_ols.f_pvalue

            f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999
            power_analysis = FTestPower()
            power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

            # Bootstrap pour l'IC de R² ajusté
            r2_adj_bootstrap = []
            for _ in range(1000):
                X_sample, y_sample = resample(X, y, replace=True)
                X_sample_ols = sm.add_constant(X_sample)
                model_sample = sm.OLS(y_sample, X_sample_ols).fit()
                n_boot, p_boot = X_sample.shape
                r2_boot = model_sample.rsquared
                r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
                r2_adj_bootstrap.append(r2_adj)

            ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
            ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

            print(f"OLS:\nR² = {r2_ols:.3f}\nadj.R² = {adjusted_r2_ols:.3f}")
            print(f"df model = {df_model} | residual = {df_resid}")
            print(f"p-value = {f_pvalue:.3f} | power = {power:.3f} | F = {f_stat:.3f}")
            print(f"RMSE = {np.sqrt(mean_squared_error(y, model_ols.predict(X_ols))):.3f}")
            print(f"IC adj.R² (95%) = [{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")

# Regression analysis + stats 2.0
# Strategies effect upon accuracy
df_statistics = df.iloc[:, [0, 10, 9]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 3:
    col_type = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if col_type:
        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]
        x_var = df_statistics.columns[2]

        df_statistics = df_statistics.groupby(participant, as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        df_statistics["mahal_dist"] = mahalanobis_distance(df_statistics, [x_var, y_var])
        threshold = np.percentile(df_statistics["mahal_dist"], 66)
        df_selected = df_statistics[df_statistics["mahal_dist"] <= threshold].copy()
        df_selected["mahal_dist"] = mahalanobis_distance(df_selected, [x_var, y_var])

        cov = np.cov(df_selected[[x_var, y_var]].T)
        mean_x, mean_y = df_selected[x_var].mean(), df_selected[y_var].mean()
        eigvals, eigvecs = np.linalg.eigh(cov)
        angle = np.degrees(np.arctan2(*eigvecs[:, 0][::-1]))
        width, height = 2 * np.sqrt(chi2.ppf(0.95, 2) * eigvals)

        X = df_statistics[[x_var]].values
        y = df_statistics[y_var].values
        X_pred = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)

        models = {
            "OLS representation": {
                "model": LinearRegression(),
                "style": {"linestyle": "-", "label": "OLS"}
            },
            "RANSAC representation": {
                "model": RANSACRegressor(),
                "style": {"linestyle": "dotted", "label": "RANSAC"}
            },
            "Theil Sen representation": {
                "model": TheilSenRegressor(),
                "style": {"linestyle": "dashed", "label": "Theil-Sen"}
            }
        }

        fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True)
        color = my_palette[0]

        for ax, (title, config) in zip(axes, models.items()):
            model = config["model"]
            model.fit(X, y)
            y_pred = model.predict(X_pred)

            inliers = df_statistics[df_statistics["mahal_dist"] <= threshold]
            outliers = df_statistics[df_statistics["mahal_dist"] > threshold]


            sns.scatterplot(data=inliers, x=x_var, y=y_var, color=color, edgecolor="black", ax=ax)
            ax.scatter(
                outliers[x_var],
                outliers[y_var],
                color=color,
                marker="x",
                s=40,
                label="Outlier"
            )

            ax.plot(X_pred, y_pred, color=color, linestyle=config["style"]["linestyle"], linewidth=0.8)
            x_pad = 0.05 * (df_statistics[x_var].max() - df_statistics[x_var].min())
            y_pad = 0.05 * (df_statistics[y_var].max() - df_statistics[y_var].min())
            ax.set_xlim(df_statistics[x_var].min() - x_pad, df_statistics[x_var].max() + x_pad)
            ax.set_ylim(df_statistics[y_var].min() - y_pad, df_statistics[y_var].max() + y_pad)

            ax.set_xlabel(x_var)
            ax.set_ylabel(y_var)

            sns.despine(ax=ax, top=True, right=True, trim=True)

        handles = [
            plt.Line2D([], [], color=color, linestyle="-", label="OLS"),
            plt.Line2D([], [], color=color, linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color=color, linestyle="dashed", label="Theil-Sen"),
        ]
        axes[-1].legend(handles=handles, title="Model", loc="upper right")

        plt.tight_layout()
        plt.show()


        # TEST PCC - regression linéaire

        X_ols = sm.add_constant(X)
        model_ols = sm.OLS(y, X_ols).fit()
        r2_ols = model_ols.rsquared
        n = X.shape[0]
        p = X.shape[1]

        adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
        df_model = int(model_ols.df_model)
        df_resid = int(model_ols.df_resid)

        f_stat = model_ols.fvalue
        f_pvalue = model_ols.f_pvalue
        f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999

        power_analysis = FTestPower()
        power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

        n_iterations = 1000
        r2_adj_bootstrap = []

        for _ in range(n_iterations):
            X_sample, y_sample = resample(X, y, replace=True)
            X_sample_ols = sm.add_constant(X_sample)
            model_sample = sm.OLS(y_sample, X_sample_ols).fit()

            n_boot = X_sample.shape[0]
            p_boot = X_sample.shape[1]
            r2_boot = model_sample.rsquared
            r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
            r2_adj_bootstrap.append(r2_adj)

        ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
        ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

        ransac = RANSACRegressor()
        ransac.fit(X, y)
        y_pred_ransac = ransac.predict(X)

        theil_sen = TheilSenRegressor()
        theil_sen.fit(X, y)
        y_pred_theil = theil_sen.predict(X)

        mse_ols = mean_squared_error(y, model_ols.predict(X_ols))
        rmse_ols = np.sqrt(mse_ols)

        mse_ransac = mean_squared_error(y, y_pred_ransac)
        rmse_ransac = np.sqrt(mse_ransac)

        mse_theil = mean_squared_error(y, y_pred_theil)
        rmse_theil = np.sqrt(mse_theil)

        ss_total = np.sum((y - np.mean(y))**2)
        ss_res_ransac = np.sum((y - y_pred_ransac)**2)
        ss_res_theil = np.sum((y - y_pred_theil)**2)

        r2_ransac = 1 - (ss_res_ransac / ss_total)

        inliers_mask = ransac.inlier_mask_
        n_total = len(y)
        n_inliers = np.sum(inliers_mask)
        inlier_ratio = n_inliers / n_total

        r2_theil = 1 - (ss_res_theil / ss_total)

        n_features = X.shape[1]
        n_min = n_features + 1
        n_samples = X.shape[0]
        n_subsamples = min(300, comb(n_samples, n_min, exact=True))
        robustness_index = n_subsamples / n_min

        adjusted_r2_ransac = 1 - ((1 - r2_ransac) * (n - 1)) / (n - p - 1)
        adjusted_r2_theil = 1 - ((1 - r2_theil) * (n - 1)) / (n - p - 1)

        print("\nComparaison des modèles de régression :\n")
        print(f"OLS :\nR²= {r2_ols:.3f}\nadj.R²= {adjusted_r2_ols:.3f}\ndf model= {df_model} | residual= {df_resid}\np-value= {f_pvalue:.3f}\npower= {power:.3f}\nF-statistic = {f_stat:.3f}\nRMSE = {rmse_ols:.3f}\nIC adj.R²(95%)=[{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")
        print()
        print(f"RANSAC:\nR²= {r2_ransac:.3f}\nR² ajusté = {adjusted_r2_ransac:.3f}\nRMSE = {rmse_ransac:.3f}\nInlier Ratio={inlier_ratio:.3f} ({n_inliers}/{n_total})")
        print()
        print(f"Theil-Sen:\nR²= {r2_theil:.3f}\nR² ajusté = {adjusted_r2_theil:.3f}\nRMSE = {rmse_theil:.3f}\nRobustness Index= {robustness_index:.1f}")

# Regression analysis + stats 3.0
# ISI effect upon accuracy
df_statistics = df.iloc[:, [0, 10, 5]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 3:
    col_type = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if col_type:
        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]
        x_var = df_statistics.columns[2]

        df_statistics = df_statistics.groupby(participant, as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        df_statistics["mahal_dist"] = mahalanobis_distance(df_statistics, [x_var, y_var])
        threshold = np.percentile(df_statistics["mahal_dist"], 66)
        df_selected = df_statistics[df_statistics["mahal_dist"] <= threshold].copy()
        df_selected["mahal_dist"] = mahalanobis_distance(df_selected, [x_var, y_var])

        cov = np.cov(df_selected[[x_var, y_var]].T)
        mean_x, mean_y = df_selected[x_var].mean(), df_selected[y_var].mean()
        eigvals, eigvecs = np.linalg.eigh(cov)
        angle = np.degrees(np.arctan2(*eigvecs[:, 0][::-1]))
        width, height = 2 * np.sqrt(chi2.ppf(0.95, 2) * eigvals)

        X = df_statistics[[x_var]].values
        y = df_statistics[y_var].values
        X_pred = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)

        models = {
            "OLS representation": {
                "model": LinearRegression(),
                "style": {"linestyle": "-", "label": "OLS"}
            },
            "RANSAC representation": {
                "model": RANSACRegressor(),
                "style": {"linestyle": "dotted", "label": "RANSAC"}
            },
            "Theil Sen representation": {
                "model": TheilSenRegressor(),
                "style": {"linestyle": "dashed", "label": "Theil-Sen"}
            }
        }

        fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True)
        color = my_palette[0]

        for ax, (title, config) in zip(axes, models.items()):
            model = config["model"]
            model.fit(X, y)
            y_pred = model.predict(X_pred)

            inliers = df_statistics[df_statistics["mahal_dist"] <= threshold]
            outliers = df_statistics[df_statistics["mahal_dist"] > threshold]


            sns.scatterplot(data=inliers, x=x_var, y=y_var, color=color, edgecolor="black", ax=ax)
            ax.scatter(
                outliers[x_var],
                outliers[y_var],
                color=color,
                marker="x",
                s=40,
                label="Outlier"
            )

            ax.plot(X_pred, y_pred, color=color, linestyle=config["style"]["linestyle"], linewidth=0.8)
            x_pad = 0.05 * (df_statistics[x_var].max() - df_statistics[x_var].min())
            y_pad = 0.05 * (df_statistics[y_var].max() - df_statistics[y_var].min())
            ax.set_xlim(df_statistics[x_var].min() - x_pad, df_statistics[x_var].max() + x_pad)
            ax.set_ylim(df_statistics[y_var].min() - y_pad, df_statistics[y_var].max() + y_pad)

            ax.set_xlabel(x_var)
            ax.set_ylabel(y_var)

            sns.despine(ax=ax, top=True, right=True, trim=True)

        handles = [
            plt.Line2D([], [], color=color, linestyle="-", label="OLS"),
            plt.Line2D([], [], color=color, linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color=color, linestyle="dashed", label="Theil-Sen"),
        ]
        axes[-1].legend(handles=handles, title="Model", loc="upper right")

        plt.tight_layout()
        plt.show()


        # TEST PCC - regression linéaire

        X_ols = sm.add_constant(X)
        model_ols = sm.OLS(y, X_ols).fit()
        r2_ols = model_ols.rsquared
        n = X.shape[0]
        p = X.shape[1]

        adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
        df_model = int(model_ols.df_model)
        df_resid = int(model_ols.df_resid)

        f_stat = model_ols.fvalue
        f_pvalue = model_ols.f_pvalue
        f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999

        power_analysis = FTestPower()
        power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

        n_iterations = 1000
        r2_adj_bootstrap = []

        for _ in range(n_iterations):
            X_sample, y_sample = resample(X, y, replace=True)
            X_sample_ols = sm.add_constant(X_sample)
            model_sample = sm.OLS(y_sample, X_sample_ols).fit()

            n_boot = X_sample.shape[0]
            p_boot = X_sample.shape[1]
            r2_boot = model_sample.rsquared
            r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
            r2_adj_bootstrap.append(r2_adj)

        ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
        ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

        ransac = RANSACRegressor()
        ransac.fit(X, y)
        y_pred_ransac = ransac.predict(X)

        theil_sen = TheilSenRegressor()
        theil_sen.fit(X, y)
        y_pred_theil = theil_sen.predict(X)

        mse_ols = mean_squared_error(y, model_ols.predict(X_ols))
        rmse_ols = np.sqrt(mse_ols)

        mse_ransac = mean_squared_error(y, y_pred_ransac)
        rmse_ransac = np.sqrt(mse_ransac)

        mse_theil = mean_squared_error(y, y_pred_theil)
        rmse_theil = np.sqrt(mse_theil)

        ss_total = np.sum((y - np.mean(y))**2)
        ss_res_ransac = np.sum((y - y_pred_ransac)**2)
        ss_res_theil = np.sum((y - y_pred_theil)**2)

        r2_ransac = 1 - (ss_res_ransac / ss_total)

        inliers_mask = ransac.inlier_mask_
        n_total = len(y)
        n_inliers = np.sum(inliers_mask)
        inlier_ratio = n_inliers / n_total

        r2_theil = 1 - (ss_res_theil / ss_total)

        n_features = X.shape[1]
        n_min = n_features + 1
        n_samples = X.shape[0]
        n_subsamples = min(300, comb(n_samples, n_min, exact=True))
        robustness_index = n_subsamples / n_min

        adjusted_r2_ransac = 1 - ((1 - r2_ransac) * (n - 1)) / (n - p - 1)
        adjusted_r2_theil = 1 - ((1 - r2_theil) * (n - 1)) / (n - p - 1)

        print("\nComparaison des modèles de régression :\n")
        print(f"OLS :\nR²= {r2_ols:.3f}\nadj.R²= {adjusted_r2_ols:.3f}\ndf model= {df_model} | residual= {df_resid}\np-value= {f_pvalue:.3f}\npower= {power:.3f}\nF-statistic = {f_stat:.3f}\nRMSE = {rmse_ols:.3f}\nIC adj.R²(95%)=[{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")
        print()
        print(f"RANSAC:\nR²= {r2_ransac:.3f}\nR² ajusté = {adjusted_r2_ransac:.3f}\nRMSE = {rmse_ransac:.3f}\nInlier Ratio={inlier_ratio:.3f} ({n_inliers}/{n_total})")
        print()
        print(f"Theil-Sen:\nR²= {r2_theil:.3f}\nR² ajusté = {adjusted_r2_theil:.3f}\nRMSE = {rmse_theil:.3f}\nRobustness Index= {robustness_index:.1f}")

# Regression analysis + stats using a covariate 3.0
# The solution for strategies effect upon accuracy by condition (TMR versus control)
!pip install boruta
!pip install pingouin
!pip install python-docx

import math
import itertools
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import numpy as np
import pandas as pd
import random
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import warnings


from boruta import BorutaPy
from docx import Document
from itertools import combinations
from math import isnan
from matplotlib.colors import Normalize
from matplotlib.cm import get_cmap
from matplotlib.colors import LinearSegmentedColormap,to_hex
from matplotlib.lines import Line2D
from matplotlib.patches import Ellipse, Patch
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from pingouin import compute_effsize, power_ttest
from scipy.interpolate import griddata
from scipy.stats import chi2, ttest_ind, pearsonr, ttest_rel, sem
from scipy.spatial.distance import mahalanobis
from scipy.special import comb, expit
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression, RANSACRegressor, TheilSenRegressor, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import resample
from statsmodels.stats.power import TTestIndPower, FTestPower
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.anova import AnovaRM, anova_lm
from statsmodels.formula.api import ols, mixedlm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multitest import multipletests
# Removed extra spaces in column names - the only way it worked
df.columns = df.columns.str.strip()

# Copying to a new DataFrame
df_statistics = df.copy()

df_statistics = df.iloc[:, [0, 10, 9, 11]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 4:
    is_3_cont = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()
    is_4_cont = df_statistics.iloc[:, 3].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if (is_3_cont and not is_4_cont) or (not is_3_cont and is_4_cont):
        print("Détection : 1 VI continue + 1 VI catégorielle multiclasses")

        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]

        if is_3_cont:
            x_var = df_statistics.columns[2]
            z_var = df_statistics.columns[3]
        else:
            x_var = df_statistics.columns[3]
            z_var = df_statistics.columns[2]

        # Regroupement
        df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        z_order = sorted(df_statistics[z_var].unique())
        palette_dict = dict(zip(z_order, my_palette))

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        models = {
            "OLS": {"model": LinearRegression(), "style": {"color": "red", "linestyle": "-", "label": "OLS"}},
            "RANSAC": {"model": RANSACRegressor(), "style": {"color": "red", "linestyle": "dotted", "label": "RANSAC"}},
            "Theil-Sen": {"model": TheilSenRegressor(), "style": {"color": "red", "linestyle": "dashed", "label": "Theil-Sen"}}
        }

        fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)

        for ax, (name, config) in zip(axes, models.items()):
            for condition in z_order:
                df_cond = df_statistics[df_statistics[z_var] == condition]

                df_cond["mahal_dist"] = mahalanobis_distance(df_cond, [x_var, y_var])
                threshold = np.percentile(df_cond["mahal_dist"], 66)
                df_sel = df_cond[df_cond["mahal_dist"] <= threshold].copy()

                inliers = df_cond[df_cond["mahal_dist"] <= threshold]
                outliers = df_cond[df_cond["mahal_dist"] > threshold]
                ax.scatter(inliers[x_var], inliers[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")
                ax.scatter(outliers[x_var], outliers[y_var],
                           c=palette_dict[condition],
                           marker="x", linewidth=1, s=120,
                           label=f"{z_var}={condition} outlier")

                if len(df_cond[x_var].unique()) < 2:
                    continue

                X_c = df_cond[[x_var]].values
                y_c = df_cond[y_var].values
                X_pred_c = np.linspace(X_c.min(), X_c.max(), 100).reshape(-1, 1)

                model = config["model"]
                model.fit(X_c, y_c)
                y_pred_c = model.predict(X_pred_c)

                ax.plot(X_pred_c, y_pred_c,
                        color=palette_dict[condition],
                        linestyle=config["style"]["linestyle"],
                        linewidth=0.8)

                ax.scatter(df_cond[x_var], df_cond[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")

            ax.set_xlabel(x_var)
            if ax == axes[0]:
                ax.set_ylabel(y_var)
            ax.set_title(name)
            sns.despine(ax=ax)

        handles = [
            plt.Line2D([], [], color="red", linestyle="-", label="OLS"),
            plt.Line2D([], [], color="red", linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color="red", linestyle="dashed", label="Theil-Sen")
        ] + [
            plt.Line2D([], [], marker='o', linestyle='', color=palette_dict[val],
                       label=f"{z_var}={val}", markeredgecolor="black", markersize=7)
            for val in z_order
        ]
        axes[-1].legend(handles=handles, loc="upper right")
        sns.despine(offset=2, trim=True)
        plt.tight_layout()
        plt.show()


# TEST STATISTIQUE - ANCOVA
#I have no idea why it didn't work, but atleast now it works
df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
    x_var: "mean",
    y_var: "mean"
})
is_repeated = df_statistics.groupby(participant)[x_var].nunique().max() > 1
# Corrected formula with backticks for column names - changed
# Wrapped the dependent variable in Q() - changed
formula = f'Q("{y_var}") ~ Q("{x_var}") + Q("{z_var}")'

model = ols(formula, data=df_statistics).fit()
aov_table = anova_lm(model, typ=2)
aov_table["eta²"] = aov_table["sum_sq"] / sum(aov_table["sum_sq"])
print(aov_table)

modalities = df_statistics[z_var].unique()
if len(modalities) > 1:
    from itertools import combinations
    comparisons = list(combinations(modalities, 2))
    p_vals, labels = [], []

    for a, b in comparisons:
        group1 = df_statistics[df_statistics[z_var] == a][y_var]
        group2 = df_statistics[df_statistics[z_var] == b][y_var]
        t_stat, p_val = ttest_ind(group1, group2, equal_var=False)
        p_vals.append(p_val)
        labels.append((a, b))

    method = "bonferroni" if len(comparisons) > 2 else "holm"
    reject, pvals_corr, _, _ = multipletests(p_vals, method=method)

    found_significant = False

    for (a, b), p_raw, p_adj, keep in zip(labels, p_vals, pvals_corr, reject):
        if keep:
            found_significant = True
            print(f"{z_var} ({a} vs {b}) - raw p = {p_raw:.3f}, corrected p = {p_adj:.3f} [{method}]")

    if not found_significant:
        print("Aucune comparaison post-hoc significative détectée.")
        #Changed, such a drama queen actually
        x_var_q = f'Q("{x_var}")'
        p_val_x = aov_table.loc[x_var_q, "PR(>F)"]
        if p_val_x < 0.05:
            print("\nEffet continu détecté: test de régression linéaire effectué)\n")

            X = df_statistics[[x_var]].values
            y = df_statistics[y_var].values

            X_ols = sm.add_constant(X)
            model_ols = sm.OLS(y, X_ols).fit()
            r2_ols = model_ols.rsquared
            n, p = X.shape

            adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
            df_model = int(model_ols.df_model)
            df_resid = int(model_ols.df_resid)
            f_stat = model_ols.fvalue
            f_pvalue = model_ols.f_pvalue

            f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999
            power_analysis = FTestPower()
            power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

            # Bootstrap pour l'IC de R² ajusté
            r2_adj_bootstrap = []
            for _ in range(1000):
                X_sample, y_sample = resample(X, y, replace=True)
                X_sample_ols = sm.add_constant(X_sample)
                model_sample = sm.OLS(y_sample, X_sample_ols).fit()
                n_boot, p_boot = X_sample.shape
                r2_boot = model_sample.rsquared
                r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
                r2_adj_bootstrap.append(r2_adj)

            ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
            ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

            print(f"OLS:\nR² = {r2_ols:.3f}\nadj.R² = {adjusted_r2_ols:.3f}")
            print(f"df model = {df_model} | residual = {df_resid}")
            print(f"p-value = {f_pvalue:.3f} | power = {power:.3f} | F = {f_stat:.3f}")
            print(f"RMSE = {np.sqrt(mean_squared_error(y, model_ols.predict(X_ols))):.3f}")
            print(f"IC adj.R² (95%) = [{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")

# Regression analysis + stats using a covariate 3.0
# The solution for insomnia level effect upon accuracy by condition (TMR versus control)
!pip install boruta
!pip install pingouin
!pip install python-docx

import math
import itertools
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import numpy as np
import pandas as pd
import random
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import warnings


from boruta import BorutaPy
from docx import Document
from itertools import combinations
from math import isnan
from matplotlib.colors import Normalize
from matplotlib.cm import get_cmap
from matplotlib.colors import LinearSegmentedColormap,to_hex
from matplotlib.lines import Line2D
from matplotlib.patches import Ellipse, Patch
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from pingouin import compute_effsize, power_ttest
from scipy.interpolate import griddata
from scipy.stats import chi2, ttest_ind, pearsonr, ttest_rel, sem
from scipy.spatial.distance import mahalanobis
from scipy.special import comb, expit
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression, RANSACRegressor, TheilSenRegressor, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import resample
from statsmodels.stats.power import TTestIndPower, FTestPower
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.anova import AnovaRM, anova_lm
from statsmodels.formula.api import ols, mixedlm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multitest import multipletests
# Removed extra spaces in column names - the only way it worked
df.columns = df.columns.str.strip()

# Copying to a new DataFrame
df_statistics = df.copy()

df_statistics = df.iloc[:, [0, 10, 5, 11]]
my_palette = ["#E15B64", "#4DDDE0", "#ABBD83", "#BEBEBE", "#FBB26D", "#A9C9D7"]
import warnings
warnings.filterwarnings("ignore")

if len(df_statistics.columns) == 4:
    is_3_cont = df_statistics.iloc[:, 2].dropna().apply(lambda x: isinstance(x, (int, float))).all()
    is_4_cont = df_statistics.iloc[:, 3].dropna().apply(lambda x: isinstance(x, (int, float))).all()

    if (is_3_cont and not is_4_cont) or (not is_3_cont and is_4_cont):
        print("Détection : 1 VI continue + 1 VI catégorielle multiclasses")

        participant = df_statistics.columns[0]
        y_var = df_statistics.columns[1]

        if is_3_cont:
            x_var = df_statistics.columns[2]
            z_var = df_statistics.columns[3]
        else:
            x_var = df_statistics.columns[3]
            z_var = df_statistics.columns[2]

        # Regroupement
        df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
            x_var: "mean",
            y_var: "mean"
        })

        z_order = sorted(df_statistics[z_var].unique())
        palette_dict = dict(zip(z_order, my_palette))

        def mahalanobis_distance(df, cols):
            cov_matrix = np.cov(df[cols].T)
            inv_cov_matrix = np.linalg.inv(cov_matrix)
            mean_vals = df[cols].mean().values
            return df[cols].apply(lambda row: mahalanobis(row.values, mean_vals, inv_cov_matrix), axis=1)

        models = {
            "OLS": {"model": LinearRegression(), "style": {"color": "red", "linestyle": "-", "label": "OLS"}},
            "RANSAC": {"model": RANSACRegressor(), "style": {"color": "red", "linestyle": "dotted", "label": "RANSAC"}},
            "Theil-Sen": {"model": TheilSenRegressor(), "style": {"color": "red", "linestyle": "dashed", "label": "Theil-Sen"}}
        }

        fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)

        for ax, (name, config) in zip(axes, models.items()):
            for condition in z_order:
                df_cond = df_statistics[df_statistics[z_var] == condition]

                df_cond["mahal_dist"] = mahalanobis_distance(df_cond, [x_var, y_var])
                threshold = np.percentile(df_cond["mahal_dist"], 66)
                df_sel = df_cond[df_cond["mahal_dist"] <= threshold].copy()

                inliers = df_cond[df_cond["mahal_dist"] <= threshold]
                outliers = df_cond[df_cond["mahal_dist"] > threshold]
                ax.scatter(inliers[x_var], inliers[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")
                ax.scatter(outliers[x_var], outliers[y_var],
                           c=palette_dict[condition],
                           marker="x", linewidth=1, s=120,
                           label=f"{z_var}={condition} outlier")

                if len(df_cond[x_var].unique()) < 2:
                    continue

                X_c = df_cond[[x_var]].values
                y_c = df_cond[y_var].values
                X_pred_c = np.linspace(X_c.min(), X_c.max(), 100).reshape(-1, 1)

                model = config["model"]
                model.fit(X_c, y_c)
                y_pred_c = model.predict(X_pred_c)

                ax.plot(X_pred_c, y_pred_c,
                        color=palette_dict[condition],
                        linestyle=config["style"]["linestyle"],
                        linewidth=0.8)

                ax.scatter(df_cond[x_var], df_cond[y_var],
                           c=palette_dict[condition],
                           edgecolor="black", linewidth=0.5,
                           alpha=1, s=40,
                           label=f"{z_var}={condition}")

            ax.set_xlabel(x_var)
            if ax == axes[0]:
                ax.set_ylabel(y_var)
            ax.set_title(name)
            sns.despine(ax=ax)

        handles = [
            plt.Line2D([], [], color="red", linestyle="-", label="OLS"),
            plt.Line2D([], [], color="red", linestyle="dotted", label="RANSAC"),
            plt.Line2D([], [], color="red", linestyle="dashed", label="Theil-Sen")
        ] + [
            plt.Line2D([], [], marker='o', linestyle='', color=palette_dict[val],
                       label=f"{z_var}={val}", markeredgecolor="black", markersize=7)
            for val in z_order
        ]
        axes[-1].legend(handles=handles, loc="upper right")
        sns.despine(offset=2, trim=True)
        plt.tight_layout()
        plt.show()


# TEST STATISTIQUE - ANCOVA
#I have no idea why it didn't work, but atleast now it works
df_statistics = df_statistics.groupby([participant, z_var], as_index=False).agg({
    x_var: "mean",
    y_var: "mean"
})
is_repeated = df_statistics.groupby(participant)[x_var].nunique().max() > 1
# Corrected formula with backticks for column names - changed
# Wrapped the dependent variable in Q() - changed
formula = f'Q("{y_var}") ~ Q("{x_var}") + Q("{z_var}")'

model = ols(formula, data=df_statistics).fit()
aov_table = anova_lm(model, typ=2)
aov_table["eta²"] = aov_table["sum_sq"] / sum(aov_table["sum_sq"])
print(aov_table)

modalities = df_statistics[z_var].unique()
if len(modalities) > 1:
    from itertools import combinations
    comparisons = list(combinations(modalities, 2))
    p_vals, labels = [], []

    for a, b in comparisons:
        group1 = df_statistics[df_statistics[z_var] == a][y_var]
        group2 = df_statistics[df_statistics[z_var] == b][y_var]
        t_stat, p_val = ttest_ind(group1, group2, equal_var=False)
        p_vals.append(p_val)
        labels.append((a, b))

    method = "bonferroni" if len(comparisons) > 2 else "holm"
    reject, pvals_corr, _, _ = multipletests(p_vals, method=method)

    found_significant = False

    for (a, b), p_raw, p_adj, keep in zip(labels, p_vals, pvals_corr, reject):
        if keep:
            found_significant = True
            print(f"{z_var} ({a} vs {b}) - raw p = {p_raw:.3f}, corrected p = {p_adj:.3f} [{method}]")

    if not found_significant:
        print("Aucune comparaison post-hoc significative détectée.")
        #Changed, such a drama queen actually
        x_var_q = f'Q("{x_var}")'
        p_val_x = aov_table.loc[x_var_q, "PR(>F)"]
        if p_val_x < 0.05:
            print("\nEffet continu détecté: test de régression linéaire effectué)\n")

            X = df_statistics[[x_var]].values
            y = df_statistics[y_var].values

            X_ols = sm.add_constant(X)
            model_ols = sm.OLS(y, X_ols).fit()
            r2_ols = model_ols.rsquared
            n, p = X.shape

            adjusted_r2_ols = 1 - ((1 - r2_ols) * (n - 1)) / (n - p - 1)
            df_model = int(model_ols.df_model)
            df_resid = int(model_ols.df_resid)
            f_stat = model_ols.fvalue
            f_pvalue = model_ols.f_pvalue

            f_squared = r2_ols / (1 - r2_ols) if r2_ols < 1 else 999
            power_analysis = FTestPower()
            power = power_analysis.power(effect_size=f_squared, df_num=df_model, df_denom=df_resid, alpha=0.05)

            # Bootstrap pour l'IC de R² ajusté
            r2_adj_bootstrap = []
            for _ in range(1000):
                X_sample, y_sample = resample(X, y, replace=True)
                X_sample_ols = sm.add_constant(X_sample)
                model_sample = sm.OLS(y_sample, X_sample_ols).fit()
                n_boot, p_boot = X_sample.shape
                r2_boot = model_sample.rsquared
                r2_adj = 1 - ((1 - r2_boot) * (n_boot - 1)) / (n_boot - p_boot - 1)
                r2_adj_bootstrap.append(r2_adj)

            ci_lower_adj_r2 = np.percentile(r2_adj_bootstrap, 2.5)
            ci_upper_adj_r2 = np.percentile(r2_adj_bootstrap, 97.5)

            print(f"OLS:\nR² = {r2_ols:.3f}\nadj.R² = {adjusted_r2_ols:.3f}")
            print(f"df model = {df_model} | residual = {df_resid}")
            print(f"p-value = {f_pvalue:.3f} | power = {power:.3f} | F = {f_stat:.3f}")
            print(f"RMSE = {np.sqrt(mean_squared_error(y, model_ols.predict(X_ols))):.3f}")
            print(f"IC adj.R² (95%) = [{ci_lower_adj_r2:.3f}, {ci_upper_adj_r2:.3f}]")